### PR TITLE
汉化

### PR DESCRIPTION
**Pull request by cyf5119**

### CODE REVIEW

**Comment by Haselnussbomber** [comment]
Thank you!

**Comment by cyf5119** [comment]
I'm very sorry, I just want to add the Chinese text to my own repositories.
However, due to my negligence, I submitted it here, which has caused trouble to you.
I'm so sorry!

**Comment by Haselnussbomber** [comment]
Oh, I thought you wanted to contribute them! :joy:
I don't mind having it translated here, but if you want I can undo it.

**Comment by cyf5119** [comment]
If you don't mind, that would be great.
But there are still some texts that I translate that are not accurate enough and require subsequent calibration.
Thank you very much!

**Pull request merged**
